apitrace/apitrace

retrace/ddrawretrace.py
This was unintentionally clearing all other lock flags, as well as
potentially having both wait and do-not-wait set simultaneously.
=> retrace: fixed DDLOCK_DONOTWAIT flag clear mask

CMakeLists.txt
Currently, the CMakeList.txt completely overwrites the CMAKE_MODULE_PATH
variable.
This is problematic when an upper-layer buildsystem wants to set its own
module path to use custom modules.
For example, Buldroot [0] provides a custom platform description [1] to
fix cross-compilation issue. Overwriting the module path means that this
custom platform description is not found:
System is unknown to cmake, create:
Platform/Buildroot to use this system, please send your config file
to cmake@www.cmake.org so it can be added to cmake
Providing such a custom platform description is what the upstream cmake
devs suggest [2], quoting:
If a toolchain file specifies CMAKE_SYSTEM_NAME such that a custom
`Platform/MySystem.cmake` file is loaded then the latter can set
them [*] as needed for the target …
=> CMakeList: do not overwrite module path

thirdparty/libbacktrace/backtrace.h, thirdparty/libbacktrace/config.h.in.cmake
HAVE_STDINT_H is used by backtrace.h
=> libbacktrace: add HAVE_STDINT_H in config.h.in.cmake

retrace/dxgiretrace.py
Some apps set WKPDID_D3DDebugObjectName private data to NULL.
=> dxgiretrace: Allow NULL pointers for WKPDID_D3DDebugObjectName.

retrace/glstate_images.cpp
Currently MSAA resolve will fail to complete framebuffer check unless this is added for depth and stencil buffers. tested and compiled.
=> Extend MSAA support to Depth Stencil

specs/glapi.py
This adds another name for glReadnPixels that might be used (e.g. virglrenderer uses it). 
Thanks for considering the patch.
=> glapi: Add support for glReadnPixelsKHR from KHR_robustness

cli/cli_sed.cpp, lib/trace/trace_callset.hpp
"trace sed" now accepts a parameter like the trim command:
--calls=CALLSET parameter
It applies the sed renaming only to those callsets specified.
Use case: Rename enums only for certain specific calls, not globally in
the whole trace.
=> Add call filtering for sed command

wrappers/memtrace.cpp
Pointers have unsigned type thus casting them to `intptr_t` could lead to a negative value which in one part of the expression is being implicitly converted to `size_t` resulting in:
`nBlocks = big_positive_number - negative_number`
This rarely happens on x64 but would often happen on x32 resulting in memory access violation.
Fixes: bac0ea039e15c219d243f2ffea40fe9b6181ce32
<details><summary>Some debugging info</summary>
<p>
That's the crash trace I've got with x32 apitrace running under wine:
```
_Z9hashBlockPKv() Address = 0x67de32bc (filename not found) [in dxgitrace.dll]
_ZN12MemoryShadow5coverEPvjb() Address = 0x67de3877 (filename not found) [in dxgitrace.dll]
_ZN24WrapID3D11DeviceContext13MapEP14ID3D11Resourcej9D3D11_MAPjP24D3D11_MAPPED_SUBRESOURCE@24() Address = 0x67cf67e5 (filename …
```
=> memtrace: Fix pointer arithmetic of MemoryShadow::cover

retrace/dxgiretrace.py
CreateDeviceAndSwapChain family of functions can accept null pSwapChainDesc.
Found when tried to record and replay a trace of looped RenderDoc's trace to find what call hangs the driver.  Call to CreateDeviceAndSwapChain in RenderDoc - [renderdoc/driver/d3d11/d3d11_replay.cpp#L3701](https://github.com/baldurk/renderdoc/blob/e4333291a112f9fbf5491e367ae900ddc837ee20/renderdoc/driver/d3d11/d3d11_replay.cpp#L3701)
=> dxgitrace: Fix null pointer dereference in createWindowForSwapChain

wrappers/memtrace.cpp
During each ::Map different pointers could be returned by DirectX.
Thus for the same resource with the same subresource having the same size
pointer may change between calls of MemoryShadow::cover. With the pointer
change number of blocks also may change, which may later cause memory
access violation in MemoryShadow::update.
=> memtrace: Update nBlocks when pointer changes in MemoryShadow::cover

wrappers/CMakeLists.txt, wrappers/glmemshadow.cpp, wrappers/glmemshadow.hpp, wrappers/gltrace.hpp, wrappers/gltrace.py
This implements handling of writeonly and read-write coherent buffers. Detailed descriptions could be found in respective commit messages.
Would close #232 
- Buffer's contents may be changed from inside the shaders however this wouldn't be reflected in shadow memory and if the same page is changed on CPU side and on GPU side even if offsets are different the data on the GPU will be overwritten.
- Small changes in buffer result in full page write.
- All readable buffers are synced back to cpu on fence signal instead of only potentially changed ones. I did not found anything that writes and reads from the same buffers with the exception of Wine which would do this if DX11 game would to such thing. Since the case is rare I didn't want to add complexity. 
On Linux:
- CS:GO - works
- Bioshock …
=> Support writable coherent buffers

wrappers/glmemshadow.cpp
This commit fixes these tests:
https://github.com/apitrace/apitrace-tests/pull/4
https://github.com/apitrace/apitrace-tests/pull/5
=> gltrace: Remove the incorrect offset in GLMemoryShadow::updateForReads()

helpers/glfeatures.cpp
Just decrease the version check. Fixes a segfault tracing an app that uses PBOs on a Raspberry Pi 4.
=> Support tracing PBOs on GLES 3.0

CMakeLists.txt, retrace/glws_waffle.cpp
Bump the waffle version requirement to 1.6 and handle the new platform
token for EGL surfaceless.
EGL surfaceless is useful when running in a headless setup, typically as
part of some CI system.
Note that for eglretrace to work correctly with EGL surfaceless a [recent](https://gitlab.freedesktop.org/mesa/waffle/commit/8a5f50234b171d227796571b8cb2c882f7a2f26f)
version of waffle is required. 
Signed-off-by: Emil Velikov <emil.velikov@collabora.com>
Signed-off-by: Alexandros Frantzis <alexandros.frantzis@collabora.com>
=> glws_waffle: Add egl surfaceless support

lib/trace/trace_model.hpp, lib/trace/trace_parser_loop.cpp, retrace/retrace_main.cpp
Call objects are unnecessarily parsed when looping on the last frame.
Parsing incurs significant CPU overhead, often limiting performance
and making Apitrace unusable for benchmarking.
https://github.com/apitrace/apitrace/issues/142
=> retrace: when looping on last frame, re-use Call objects

wrappers/dlsym.cpp
uClibc defines the ```__GLIBC__``` macro too (I know, right?), so verify that
```__UCLIBC__``` is not defined before we can use glibc-specific internal
functions.
Signed-off-by: Paul Cercueil <paul@crapouillou.net>
=> dlsym: Fix build under uClibc

retrace/glretrace.hpp, retrace/glretrace.py, retrace/glretrace_main.cpp, specs/glapi.py
These patches enable Linux/Windows retrace for GFXBench AztecRuins and Bioshock Infinite.
I'm happy to re-write if there is a better way to do the code generation.
=> Support cross-platform retrace for titles that query uniforms by index

dispatch/glproc_gl.cpp
Same as https://github.com/apitrace/apitrace/commit/508a26ab7d613a82d8024309582dd34f400ded8e but for `glproc_gl.cpp`
=> Support libc that don't have RTLD_DEEPBIND

gui/mainwindow.cpp
This PR changes the "x" letter used instead of multiplication sign in texture sizes (e.g. _16 x 32_ instead of _16 × 32_), and adds the size of the third dimension, depth, for the textures for which it's relevant.
=> Show depth for 3D textures

cli/CMakeLists.txt, cli/cli.hpp, cli/cli_info.cpp, cli/cli_main.cpp, lib/trace/trace_api.hpp
The new 'info' client prints the provided trace file information. The
first version of the client shows the container version, api type and
the total amount of frames in the trace file. The information can be
printed in JSON format.
=> Add the new client application 'info'

retrace/glws_glx.cpp
Pixel buffers are allowed to be used in glXSwapBuffers.
glx 1.4 spec, 3.3.5 "Off Screen Rendering", "glXCreatePbuffer":
"The resulting pbuffer will contain color buffers and ancillary
buffers as specified by config. It is possible to create
a pbuffer with back buffers and to swap the front and back
buffers by calling glXSwapBuffers."
Fixes replaying of Blender traces.
=> glws_glx: Allow pixel buffers in GlxDrawable::swapBuffers

wrappers/gltrace.py
Otherwise these writes would be lost. Deus Ex: Mankind Divided renders incorrectly without this.
=> gltrace: Commit all writes to coherent buffers before syncing them back

gui/pixelwidget.cpp
There are zoom hotkeys (+/-), grid hotkeys (g, PgUp, PgDown), etc that don't seem to work when viewing an image of a texture. This change allows PixelWidget to get keyboard focus.
=> gui: fix keyboard focus to make hotkeys work in image viewer

cli/cli_info.cpp, lib/trace/trace_file.hpp, lib/trace/trace_file_brotli.cpp, lib/trace/trace_file_snappy.cpp, lib/trace/trace_file_zlib.cpp, lib/trace/trace_parser.hpp
Added extra information to cli_info output which includes:
* container type (compression method)
* container size (the size of the data in the storage container)
* actual data size (the size of uncompressed data)
* per frame metrics which include the folowing information:
* first call_id
* last call_id
* the total amount of calls in a frame
* uncompressed frame size
Usage:
`  apitrace info --dump-frames /path/to/file.trace`
An example output:
```
{
"FileName": "/path/to/file.trace",
"ContainerVersion": 6,
"ContainerType": "Snappy",
"API": "OpenGL + GLX/WGL/CGL",
"FramesCount": 1789,
"ActualDataSize": 5272672851,
"ContainerSize": 1547699157,
"Frames": [{
"FirstCallId": 0,
"LastCallId": 2231,
"TotalCalls": 2232,
"SizeInBytes": 1259924
}, {
"FirstCallId": 2232,
"LastCallId": 2251, …
```
=> cli_info: Dump per frame metrics for trace files

specs/glapi.py
Thank you so much for maintaining this tool!  It's an absolute godsend for debugging any kind of graphics issue in our engine.
This change makes it possible for apitrace to work with applications that use SPIR-V shaders.  Without this, glLinkProgram would fail and glretrace would crash.
Thanks for your consideration!
=> glapi: Add glSpecializeShaderARB from GL_ARB_gl_spirv

docs/USAGE.markdown, retrace/glretrace.hpp, retrace/glretrace_egl.cpp, retrace/glretrace_glx.cpp, retrace/glretrace_main.cpp, retrace/glretrace_wgl.cpp, retrace/retrace.hpp, retrace/retrace_main.cpp
Hello there,
The commit messages should be explicative enough:
```
When replaying a trace, it could be useful to analyze how much time is
needed to render and present each frame. While developing a GPU driver,
for example, developers could graph the frame time series in order to
detect regressions or improvements of driver performance over time.
The `--pframe-times` option enables profiling for frame times, meaning
that replaying will output a timestamp when a frame has been presented.
```
I guess this is a first draft of something that needs some more work.
At the current state, this option works only on `wgl`, `glx`, and `egl` backends.
Please, tell me what I am missing, and how I could tackle that. 😃
=> retrace: Print frame times

gui/apitracecall.cpp
Also add a thin no-break space between the number and the unit, and use
a larger set of units, with explicitly-binary prefixes: i.e. KiB, MiB, GiB.
=> Avoid exponential notation when showing binary data size

lib/trace/trace_dump.cpp, lib/trace/trace_dump_internal.hpp
Fixes compilation on Ubuntu 20.10 on s390x
=> trace: Move visitString template to the header file

gui/apicalldelegate.cpp, gui/apitracecall.cpp, gui/apitracecall.h, gui/apitracemodel.cpp, gui/mainwindow.cpp, gui/mainwindow.h, gui/retracer.cpp, gui/retracer.h, gui/ui/mainwindow.ui, retrace/retrace_main.cpp
In retracer calls can be disabled with:
`  --ignore-calls=CALLSET    ignore calls in CALLSET`
In QApiTrace:
-    Call range can be disabled/enabled with "Toggle Calls" ctrl+/
-    All disabled calls could be enabled with "Enable All Calls"
I've been using this for quite some time and it proved to be useful in investigations of hangs, misrenders, and other issues with Mesa.
=> retrace,gui: Add ability to disable specific calls

retrace/metric_backend_opengl.cpp
By running `eglretrace --pframes "opengl: GPU Duration" test.trace`, we would see a column with GPU time for each frame of the trace, but the actual value is incorrect.
That is because GPU duration relies on GPU start. If that is not enabled with "opengl: GPU Start", we end up using a uninitialized value, resulting in undefined behavior.
With this commit, we make sure GPU start is valid before calculating GPU duration.
=> retrace: Fix GPU Duration

lib/image/image.hpp, retrace/glstate_images.cpp
E.g. the crash could be reproduced with this trace: [gl-3.2-layered-rendering-gl-layer-render.trace.zip](https://github.com/apitrace/apitrace/files/5642748/gl-3.2-layered-rendering-gl-layer-render.trace.zip)
=> glstate: Fix out-of-bounds memset of image

gui/main.cpp
`QSettings` requires that the application and organisation names are initialised before it can use an implicit settings location. When
QApiTrace uses `QSettings`, it doesn't set an explicit location, so the implicit one must be valid.
Without this, the *Recent Launches* list remains empty, at least on Windows. I've had it work on Ubuntu, though, so presumably something's setting the names automatically there.
=> Initialise application name

gui/CMakeLists.txt, gui/adaptivedoublespinbox.cpp, gui/adaptivedoublespinbox.h, gui/imageviewer.cpp, gui/imageviewer.h, gui/pixelwidget.cpp, gui/pixelwidget.h, gui/ui/imageviewer.ui
Center the image, focus PixelWidget at start to make keys work, allow zoom < 1, add a checkbox to auto-fit the image (stops fitting when manually zoomed), save auto-fit option after restart.
=> gui: zoom to fit in image viewer

retrace/glws_glx.cpp
Otherwise we may get a pbuffer with configuration incompatible
with a context.
Fixes replaying of traces of Substance Painter.
Found in: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3271
Trimmed trace which reproduces the crash (at least on Mesa): 
[substance_painter_trimmed.zip](https://github.com/apitrace/apitrace/files/5055602/substance_painter_trimmed.zip)
=> glws_glx: Choose pbuffer's attribs according to visual info

CMakeLists.txt
Prevents from configuring dependent libraries for a wrong/unsupported compiler.
=> Makes MSVC version check earlier

thirdparty/libbacktrace/CMakeLists.txt, thirdparty/libbacktrace/ChangeLog, thirdparty/libbacktrace/alloc.c, thirdparty/libbacktrace/atomic.c, thirdparty/libbacktrace/backtrace-supported.h.in, thirdparty/libbacktrace/backtrace.c, thirdparty/libbacktrace/backtrace.h, thirdparty/libbacktrace/btest.c, thirdparty/libbacktrace/dwarf.c, thirdparty/libbacktrace/elf.c, thirdparty/libbacktrace/fileline.c, thirdparty/libbacktrace/internal.h, thirdparty/libbacktrace/mmap.c, thirdparty/libbacktrace/mmapio.c, thirdparty/libbacktrace/nounwind.c, thirdparty/libbacktrace/pecoff.c, thirdparty/libbacktrace/posix.c, thirdparty/libbacktrace/print.c, thirdparty/libbacktrace/read.c, thirdparty/libbacktrace/simple.c, thirdparty/libbacktrace/sort.c, thirdparty/libbacktrace/state.c, thirdparty/libbacktrace/stest.c, thirdparty/libbacktrace/testlib.c, thirdparty/libbacktrace/testlib.h, thirdparty/libbacktrace/unknown.c
GCC 10 changed from defaulting from dwarf-v4 to dwarf-v5. The bundled libbacktrace is somewhat old and does not yet support dwarf-5. This results in libbacktrace_btest failing with
unrecognized DWARF version in .debug_info at 6
Note: libbacktrace_btest will fail with current cmake versions if run through ctest due to [1], specifically it will fail with
ERROR: descriptor 3 still open after tests complete
Even though this is a cmake bug, perhaps it might be appropriate to adapt btest.c to omit checking whether fd 3 is still open. I can modify the PR accordingly if desired.
[1] https://gitlab.kitware.com/cmake/cmake/-/issues/18863
=> Update bunded libbacktrace for dwarf-5 support

frametrim/ft_dependecyobject.cpp, frametrim/ft_dependecyobject.hpp, frametrim/ft_frametrimmer.cpp
Add support for glClipControl. glCreateBuffers, glTextureBarrier,  glVertexAttrib(Binding|Format|Divisor), 
add all bound buffers when drawing as a dependency, and emit buffer that is written to by using memcopy in a preserved frame. These changes make it possible to trim traces obtained from Tomb Raider 2013.
=> Gltrim: add handling various function calls and fix used of pipelines 

retrace/d3dretrace.hpp, retrace/glretrace_main.cpp, retrace/glstate.hpp, retrace/glstate_images.cpp, retrace/retrace.hpp, retrace/retrace_main.cpp
When specifying "--snapshot=frame" it can be assumed that the user
is interested in the renderung output that goes to the screen and
not to some framebuffer attachment that happens to be bound to be
bound to an active framebuffer and set to be the drawbuffer.
Consequently, override the frame capture logic in case the frame-end
call triggers the snapshot to get the backbuffer contents.
Closes: #699
=> retrace: take end of frame shapshots always from back buffer

frametrim/ft_dependecyobject.cpp, frametrim/ft_dependecyobject.hpp, frametrim/ft_frametrimmer.cpp
gltrim: 
* Handle indirect and instanced draw calls
* Handle CopyBufferSubData and CopyNamedBufferSubData
* 
Some of these calls are used with "The Dark Mod"
=> Gltrim add copysubdata and indirect draw

retrace/glretrace_egl.cpp
Avoids an “unsupported eglGetPlatformDisplayEXT call” warning when replaying a `gtk4-demo` trace from Wayland.
The same ignore was done for `eglGetDisplay()`.
Signed-off-by: Emmanuel Gil Peyrot <linkmauve@linkmauve.fr>
=> glretrace: Ignore eglGetPlatformDisplay*()

frametrim/ft_frametrimmer.cpp, frametrim/ft_frametrimmer.hpp, frametrim/ft_main.cpp
It seems that call IDs in traces are not necessarily ordered,
so don't rely on an ascending order. 
This fixes trimming a Tom Raider 2013 trace.
@jrfonseca This is a workaround, I guess the real fix would be to make sure that the call IDs are indeed ascending, but I didn't really find the code that is responsible for writing the calls in any order. If you can point me to it, I can try to figure out why the call IDs might be written out of order.
=> gltrim: allow unordered call IDs when copying calls out of a trace

retrace/retrace_main.cpp
Defaulting to reading from the back buffer when snapshots are taken at
frame frequency broke some test that only use FBOs and not always
clear the back buffer properly so that garbage was read back.
Add an option that the caller can force reading from the backbuffer,
but default to the old behaviour of reading back from the currently
bound draw buffer.
Fixes: 3d7d6e16606542e3255e03d8e99335aece7e5cdf
retrace: take end of frame shapshots always from back buffer
=> retrace: Add an option to force using the back buffer as snapshot source

frametrim/ft_dependecyobject.cpp
In OpenGL deleting a non-existing object is siletly ignored, so
check if the object exists before attaching the delete call to it.
Closes: #714
=> gltrim: ignore non-existing objects when calling delete or destroy

retrace/glretrace.py, retrace/retrace.cpp, retrace/retrace.hpp, retrace/retrace_main.cpp
By default reading back query results is skipped, this commit adds the option to actually read back the query result and then either ignore it (useful for performance analysis, because reading back the result may trigger some synchronization, e.g. with the virgl driver), or check the result against the previously recorded one.
=> replay: Add option to execute and check queries

gui/ui/imageviewer.ui
I needed to be able to restrict the range to 0.9998-1.0 to be able to see something far away in a depth buffer, so made this change locally as three decimal digits didn't let me specify such a small range. Presumably, someone else might want to visualise tiny depth buffer differences, too.
=> Increase precision of image range spinners

gui/mainwindow.cpp, gui/retracer.cpp, gui/retracer.h, gui/ui/retracerdialog.ui, retrace/glretrace.py, retrace/retrace.cpp, retrace/retrace.hpp, retrace/retrace_main.cpp
In order to reduce the noise when comparing recorded query values
to evaluated ones while retracing add an option to be able to
specify a threshold for the result difference.
With a threshold > 0 " --query-handling check" will be enabled too.
Related: #715
Signed-off-by: Gert Wollny <gert.wollny@collabora.com>
=> retrace: Add option to pass a query result check threshold

helpers/glfeatures.hpp, retrace/glretrace.hpp, retrace/glretrace_cgl.cpp, retrace/glretrace_egl.cpp, retrace/glretrace_glx.cpp, retrace/glretrace_wgl.cpp, retrace/glretrace_ws.cpp
Check the calls that configure the framebuffer format and use the
requested samples value unless this value was set from the command
line.
WIP: currently calling the framebuffer config twice with different samples values will result in ignoring the second value if the first one was != 1. 
Related: #690 
@jrfonseca could you skim over it to see whether this makes any sense?
=> glretrace: use samples value recorded in trace to set MSAA samples

frametrim/ft_dependecyobject.cpp, frametrim/ft_dependecyobject.hpp, frametrim/ft_frametrimmer.cpp
- keep MSAA info in trace (fixes the gltrim tests that broke when we started to replay with the MSAA info)
- fix buffer bindings, mapping and unmapping 
- fix reading textures from unpack buffers 
- add proper support for BindVertexArray
=> Various gltrim fixes

retrace/retrace_main.cpp
Found upon inspection.
Fixes: 93ac817a ("d3dretrace: Partial support for choosing discrete/integrated GPU.")
Signed-off-by: Andres Gomez <agomez@igalia.com>
=> retrace: remove redundant comparison for the --driver option values

retrace/metric_backend_opengl.cpp, retrace/metric_backend_opengl.hpp
Ask the OpenGL implementation what resolution it supports and handle any
roll overs that could have happened.
Signed-off-by: Tomeu Vizoso <tomeu.vizoso@collabora.com>
=> retrace: Handle timestamp counter roll-overs

frametrim/ft_dependecyobject.cpp, frametrim/ft_dependecyobject.hpp, frametrim/ft_frametrimmer.cpp
- glRenderMode,
- glPushAttrib, glPopAttrib, glClientPushAttrib, glPopClientAttrib
- glNamedProgramLocalParameter
- glNamedProgramEnvParameter
- glActiveStencilFace
- glMultiTexCoord
- OpenGL 2.1 allows a texture to be created with the bind call so add the texture object on bind if it doesn't exist
- avoid segfault when the vertex array is unbound
=> gltrim: some more fixes and handling of additional calls

specs/glxapi.py
The call to glXChooseFBConfig defines the attrib_list as pointer to int.
Fixes replaying and traces of "Lifeless Planet"
Remark: Maybe all the values should be defined as Int.
=> specs/glxapi: Make GLX_SAMPELES and GLX_SAMPLE_BUFFERS accept int

frametrim/ft_frametrimmer.cpp
This is required for trimming "Sir, You Are Being Hunted" (but #741 is also required)
=> gltrim: Handle glNormalPointer, glMultiTexCoord and a few  glX calls

.github/workflows/build.yml
Apparently Ubuntu may also drop package versions in LTS
distros, so always run "apt-get update" before trying to
install packages.
case in point: https://github.com/gerddie/apitrace/runs/2873510746?check_suite_focus=true
=> workflows: Update package list on ubuntu64*

retrace/glstate_shaders.cpp
When `AttribDesc::AttribDesc` fills in the data fields, it tries to find number of columns from size and type only. This works OK for uniforms (and presumably feedback transform attributes), because they can have type like `GL_FLOAT_VEC3`, but this fails for vertex attributes, where types can only be scalar (those acceptable to `glVertexAttribPointer`).
This patch special-cases filling in the data fields for vertex attributes, which then lets `qapitrace` show the correct structure of vertex buffers.
=> Fix dumping vertex attributes

retrace/glstate_shaders.cpp
Current code relies on there being only one attribute per stride, and
gives wrong results when this assumption is broken. This patch fixes
this and closes #751.
=> Fix calculation of vertex attribute count

retrace/glretrace.py
glDeleteBuffers ignores non-existing buffers names, and especially '0',
but calling glGetNamedBufferPointerv on a non-existing buffer results in
an error 'GL_INVALID_OPERATION'. To avoid this error skip over buffer '0'
when handling the region pointers.
Signed-off-by: Gert Wollny <gert.wollny@collabora.com>
=> glretrace: Don't try to get pointer for buffer '0' in DeleteBuffers

frametrim/ft_dependecyobject.cpp, frametrim/ft_frametrimmer.cpp
Blender 3D 2.80+ uses shared contexts,with this series its traces can be trimmed.
=> GLtrim: track shared and per-context resources 

retrace/dxgiretrace.py, retrace/retrace_swizzle.cpp, specs/dxgi.py
- Adds support for IDXGIFactory7
- Fixes non-default adapters in `EnumAdapterByGpuPreference`
- Handles returning non-default adapters for EnumAdapterByLuid (these are never going to match up)
- Fix the `intersects` region call on 64-bit
=> Add support for newer DXGI, misc fixes

retrace/process_name.cpp
We use this in DXVK for app profiles so we need this to be spoofed like this too on retrace.
Signed-off-by: Joshua Ashton <joshua@froggi.es>
=> retrace: Add support for spoofing GetModuleFileNameW

helpers/floating_point_conversion.hpp, retrace/glstate_shaders.cpp, wrappers/config.cpp, wrappers/config.hpp, wrappers/glcaps.cpp
The first patch fixes a bug when an incomplete set of configuration values was given in the config file. In this case we should fall back to the values provided by the driver. 
The second patch adds the possibility to set minimum values for buffer alignment offsets, so that one can prepare a trace on one type of hardware that might set lower limits than some other hardware one wants to replay the traces on.
=> More config overrides

retrace/glretrace_egl.cpp, retrace/glws.hpp, retrace/glws_egl_xlib.cpp
These seem to be functional, although I'm not sure if this is the correct way to implement it in apitrace. Just let me know if something can be improved.
=> egltrace: implement eglSetDamageRegion/eglSwapBuffersWithDamage on retrace

frametrim/ft_dependecyobject.cpp
Fixes:
```
26916: glActiveTexture Invalid texture unit 34015 specified, ignoring call
```
Found-by: Gert Wollny <gert.wollny@collabora.com>
Signed-off-by: David Heidelberg <david.heidelberg@collabora.com>
=> frametrim: fix active texture check compare

retrace/glws_waffle.cpp
Synchronize error report with non-waffle version and make it a bit useful.
Signed-off-by: David Heidelberg <david.heidelberg@collabora.com>
=> retrace: when waffle_context_create fails, report GL context version

frametrim/ft_dependecyobject.cpp, frametrim/ft_dependecyobject.hpp, frametrim/ft_frametrimmer.cpp, frametrim/ft_frametrimmer.hpp, frametrim/ft_main.cpp
In order to be able to loop the last frame we must not destroy objects
that are used in the last frame but not created there. For simplicity
only check whether the object was created in the last frame, and not
emit the delete code if it was not.
Remark: 
This doesn't cover all cases where looping the last frame will fail, e.g. buffer mappings or context creation and destruction may also lead to crashes.
=> gltrim: retain objects in the last frame that were created in earlier frames 

frametrim/ft_frametrimmer.cpp
Just like with the corresponding glX calls ignore
eglGetCurrentContext, eglGetCurrentDisplay, and
eglGetCurrentSurface and keep eglDestroyContext and
eglDestroySurface.
Closes: #808
Signed-off-by: Gert Wollny <gert.wollny@collabora.com>
=> gltrim: handle a few more EGL calls

docs/BUGS.markdown
`apitrace repack -b` seems to be more effective than repacking with xz or lzma.
=> docs: update attachment procedure for trace

CMakeLists.txt, cli/CMakeLists.txt, cli/cli.hpp, cli/cli_main.cpp, cmake/GenerateVersion.cmake, gui/CMakeLists.txt, gui/main.cpp, version.h.in
Currently supports:
- `apitrace version`
- `qapitrace -v` or `qapitrace --version`
when having installed system and custom apitrace from git, it comes handy.
One thing to discuss is dependency on the git.
References: https://github.com/apitrace/apitrace/issues/493#issuecomment-253976844
=> implement versioning support

helpers/eglsize.cpp
It is currently creating a texture then attempting to delete it as a buffer.
=> Fix bug in _EGLImageKHR_get_image_info

retrace/retrace_main.cpp
Add a flag to abort the trace if a single call takes too long.
=> Retrace: Add retrace watchdog flag

specs/d3d8.py
D3D8 uses DWORD handles instead of shader objects. The specific values of these handles is not defined, so it is best to remap them like we do with GL handles.
This fixes issues where a D3D8 trace will cause errors when run with [d8vk](https://github.com/AlpyneDreams/d8vk) or vice-versa.
=> d3d8trace: Remap shader handles

specs/d3d8.py
Similar to #836, D3D8 uses DWORD handles instead of state block objects. We have to track them like GL handles.
Similarly, this fixes crashes when replaying traces on alternate D3D8 implementations such as [d8vk](https://github.com/AlpyneDreams/d8vk).
=> d3d8trace: Remap state block handles

frametrim/ft_dependecyobject.cpp, frametrim/ft_dependecyobject.hpp, frametrim/ft_frametrimmer.cpp, frametrim/ft_frametrimmer.hpp, frametrim/ft_main.cpp
This is a series to alleviate the problems reported in https://github.com/apitrace/apitrace/issues/839
With these patches a new call flag is added to tag calls that may be dropped after the first time when the last frame is looping. gltrim will tag these calls, and the a new retrace flag is added `--loop-skip-tagged-calls` to actually skip these calls during replay with the final loop. 
Testing with the trace posted in #839 showed a *significant* impact on performance, so using this  flag in a context where the performance is analyzed may not be a good option. 
The nice thing about this approach is that one can simply re-trim already trimmed traces. 
An alternative would be to either inject  object destroy calls for objects that are created but not deleted in the last frame (This is …
=> Gltrim skip while looping

retrace/glstate_params.py
This is useful in case we (or implementation) misunderstood specs and read scalar where it is an array.
=> #848. Check for buffer overflow in case of scalar glGet[Integer]v.

lib/image/image.hpp
This is done for a rare case of buggy driver, which writes more bytes than we expect (and specs say). I have a particular problem on reading very low-resolution textures on Windows + AMD RX 550, and the problem totally blocks retracing for me.
Note that we write a 4-byte marker immediately after the image contents and assert that it has not changed in destructor. So if driver is buggy, we can see it in Debug build, but Release build simply proceeds.
=> #850. Add a bit of excessive space in image buffer.

frametrim/ft_frametrimmer.cpp, frametrim/ft_frametrimmer.hpp, frametrim/ft_main.cpp
In order to not accumulate too much work in the setup frame add the option to replace the buffers swaps that would be happening there with glFinish to submit the work to the graphics card. This is useful for the Mesa-CI.
=> gltrim: Add option to replace swaps in setup with glFinish

specs/dwrite.py, specs/stdapi.py, wrappers/d2d1trace.py
The `winnt.h` header seems to have changed recently and there is a `WIN_NOEXCEPT` exception specification added to `DWriteCreateFactory`. It is either defined as `noexcept` or `throw()` depending on the compiler version. If `WIN_NOEXCEPT` is not defined, it means we have an older version of the header, so we define it as empty.
=> wrappers: add noexcept specification to DWriteCreateFactory

gui/mainwindow.cpp, gui/ui/retracerdialog.ui
The retracer dialog had a lot of weird things going on. This should improve it so it looks right on all platforms.
=> Improve the layout of the retracer dialog

retrace/glws_waffle.cpp
Without this patch, replaying an eglDestroySurface() call won't generate a eglDestroySurface() call using the waffle backend, leaving any created windows alive indefinitely.
=> retrace: call waffle_destroy_window on drawable destructor

gui/apitracecall.cpp
Building apitrace like this on macOS causes issues:
```bash
cd apitrace
mkdir build
cd build
cmake -DENABLE_GUI=ON -DENABLE_QT6=ON ..
make
```
Eventually it ends with this error:
```
Building CXX object gui/CMakeFiles/qapitrace.dir/apitracecall.cpp.o
/Users/fox/Projects/apitrace/gui/apitracecall.cpp:1100:40: error: use of overloaded operator '+' is ambiguous (with operand types 'QString' and 'QLatin1String')
m_searchText = m_signature->name() + QLatin1String("(");
~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~
/opt/homebrew/include/QtCore/qstring.h:1524:16: note: candidate function
inline QString operator+(QString &&lhs, const QString &rhs)
^
/opt/homebrew/lib/QtCore.framework/Headers/qstringbuilder.h:404:1: note: candidate function [with A = QString, B = QLatin1String]
operator+(const A &a, …
```
=> Avoid compilation error with ambiguous `QString + QLatin1String`

lib/os/os_posix.cpp, lib/os/os_string.hpp, lib/os/os_win32.cpp, lib/trace/trace_writer_local.cpp, retrace/process_name.cpp, retrace/process_name.hpp, retrace/retrace_main.cpp
Some middleware libraries and/or drivers may detect applications based on executable name and command line. Apitrace currently saves executable name in the trace and then injects its own implementation of some syscalls during replay to return this name.
This PR adds this functionality to command line to further enhance the illusion of replayed app being the real app. Currently only fully implemented on Windows.
=> Fake command line arguments during replay, so they match traced program's arguments

cli/cli_trace.cpp, lib/trace/trace_option.cpp, lib/trace/trace_writer_local.cpp
This is useful when traces are generated in an automated fashion or handled by some manager auto-restarting the process. This gives more information about the different trace files generated.
`TRACE_TIMESTAMP` environment variable can be used when using the wrappers directly without using the CLI to start tracing.
=> Add option to append timestamp to generated trace filename

specs/eglapi.py
It doesn't make sense to show modifiers as a decimal value and they are easier to parse with the hexadecimal representation. 
This add a new API type (`Formatted`)  that is serialized as a `Repr` value in the trace file. The values are gonna show up properly as long as the newest version of apitrace (with these patches) is used to generate the trace as the human value is embedded in the file.
=> Display format modifiers as hexadecimal values

cli/cli_trace.cpp, lib/trace/trace_writer_local.cpp, specs/eglapi.py
- Fix "-t" short option
- Don't mutually exclude "--timestamp" and "--output" options
- Dump the enum value name for compression rates instead of the value
=> Some fixes related to the MRs I opened earlier

retrace/glretrace_main.cpp, retrace/metric_backend_opengl.cpp, retrace/metric_backend_opengl.hpp
All GPU timestamp related metrics (and GPU profiling "-pgpu") are now available if the GPU supports EXT_disjoint_timer_query OpenGL extension.
Add "GPU Disjoint" metric for OpenGL backend (only possible to enable if "GPU Duration" is queried as well)
Fixes [689](https://github.com/apitrace/apitrace/issues/689)
=> Add support for profiling with EXT_disjoint_timer_query

retrace/glretrace_main.cpp, retrace/metric_backend_opengl.cpp, retrace/metric_backend_opengl.hpp
Even though the Mesa drivers are aliasing the EXT API calls with the unsuffixed versions, it doesn't work with all drivers (e.g. libmali). Selecting the right call to use depending on the supported extensions makes it work universally.
=> retrace: Use right API calls when using EXT_disjoint_timer_query

frametrim/ft_dependecyobject.hpp, retrace/metric_writer.cpp
Fix building with GCC-15. It no longer includes it by default.
> apitrace-9.0/retrace/metric_writer.cpp: In static member function
> ‘static void ProfilerQuery::writeMetricEntryCallback(Metric*, int, void*, int, void*)’:
> apitrace-9.0/retrace/metric_writer.cpp:50:70: error: ‘uint64_t’ does not name a type
> 50 |         case CNT_NUM_UINT64: std::cout << "\t" <<
> *(reinterpret_cast<uint64_t*>(data)); break;
> |
> ^~~~~~~~
> apitrace-9.0/retrace/metric_writer.cpp:29:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; 
> this is probably fixable by adding ‘#include <cstdint>’
>   28 | #include "metric_writer.hpp"
>  +++ |+#include <cstdint>
>   29 |
> apitrace-12.0/frametrim/ft_dependecyobject.hpp:31:1:
> note: ‘uint32_t’ is defined in header ‘<cstdint>’; 
> this is probably fixable by …
=> Explicit header: stdint

retrace/metric_backend_opengl.cpp
After the API calls refactoring, we got a typo in GPU duration, which basically made all measurements became zero-valued, since it was subtraction GPU start timestamp with itself.
Fixes: 1937ee8eb5e5ef816481b283ec9850f62132b043
---
Before
```
eglretrace --headless --benchmark --singlethread --loop=5 --pframes "opengl:GPU Duration" /tmp/replayer-db/unvanquished/unvanquished-lowest.trace 
warning: --loop blindly repeats the last frame calls, therefore frames might not necessarily render correctly (https://github.com/apitrace/apitrace/issues/800)
/app/lib/daemon
frame   0
frame   0
frame   0
frame   0
frame   0
frame   0
frame   0
frame   0
Rendered 7 frames in 1.04942 secs, average of 6.67036 fps
```
---
After
```
$ eglretrace --headless --benchmark --singlethread --loop=5 --pframes …
```
=> retrace: Fix GPU Duration calculation

retrace/d3d9retrace.py
`D3DPRESENT_INTERVAL_TWO`, `D3DPRESENT_INTERVAL_THREE`, `D3DPRESENT_INTERVAL_FOUR` are not supported in windowed mode. (See https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3dpresent)
So if we force windowed mode, we also need to adjust the presentation interval otherwise the trace will just fail at device creation.
=> d3d9retrace: Adjust presentation interval when forcing windowed mode

gui/qubjson.cpp
> gui/qubjson.cpp: In function QString readChar(QDataStream&):
> gui/qubjson.cpp:151:19: error: no matching function for call to QChar::QChar(qint8&)
>  151 |     return QChar(c);
implicit conversions are disabled for QChar::QChar with [qt-6.9](https://doc.qt.io/qt-6.9/qchar.html#QChar-3)
=> fix qt-6.9

retrace/glws_egl_xlib.cpp, retrace/retrace_main.cpp
We have a number of apitraces that we'd like to use for driver performance work with perfetto or MESA_GPU_TRACES=print_*, but we can't because a lack of cleanup of the window system means that the output gets arbitrarily truncated.
I've now confirmed that my screen gets destroyed on an EGL and a GLX trace from traces-db, with and without waffle.  TBD: d3d.
=> Re-enable and fix GL window system cleanup
